refactor
matsui54/ddu-source-help pull request #26
Opened 2023-06-10 16:31 UTC by uga-rosa

Use flatMap instead of for nesting.

This is not a bug fix, so you can close it if it is not to your taste.

2023-06-11 01:45 UTC, uga-rosa commented on denops/@ddu-sources/help.ts
> +                if (seg.length < 3) return;
With 2, the pattern can be undefined.

2023-06-11 01:46 UTC, uga-rosa commented on denops/@ddu-sources/help.ts
> +            if (args.sourceParams.style === "minimal" || infos.length < 2) {
We should use the strict equality (===) operator.

2023-06-11 01:48 UTC, uga-rosa commented on denops/@ddu-sources/help.ts
>                  const [tag, path, pattern] = seg;
With 2, `pattern` can be undefined.

2023-06-12 08:48 UTC, matsui54 commented
This PR looks good. Is there something wrong?

2023-06-12 15:03 UTC, uga-rosa commented
I have many other changes I would like to make for my own use, and I am using the forking version with many changes.
Shall I reopen this?

2023-06-13 02:46 UTC, matsui54 commented
OK! Please let me know if it's ready to merge.

2023-06-13 03:22 UTC, uga-rosa commented
Ok. You can merge this PR.

2023-06-20 15:17 UTC, uga-rosa commented
🤔

2023-06-21 09:21 UTC, matsui54 requested changes

2023-06-21 09:22 UTC, matsui54 commented
Sorry, I didn't realize my review was pending🙇

2023-06-21 09:25 UTC, uga-rosa commented
I see.
Fixed.

2023-06-21 09:25 UTC, merged